#!/usr/bin/env python3
'''
This is a radis implemented module for caching
information.
'''
import uuid
import redis
from typing import Union


class Cache:
    '''
    The Cache class store an instance of a redis client
    flushes the db and implements methods to save the data.
    '''

    def __init__(self) -> None:
        '''
        This is the first method called at the instance of
        the class Cache.
        '''
        self._redis = redis.Redis()
        self._redis.flushdb()

    def store(self, data: Union[str, bytes, int, float]) -> str:
        '''
        This method takes a data arguments and returns the key
        used to map data in the redisDB. This key is generated by
        uuid.
        '''
        uid = str(uuid.uuid4())
        self._redis.set(uid, data)
        self._redis.save()
        return uid
